[tool.poetry]
name = "bookclub"
version = "0.1.0"
description = ""
authors = ["ledenevs <sergei.ledenev@adsum-works.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

